name: flutter_module
description: A new Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: 'task/task_v1.12.13_support_hotfixes'
  cupertino_icons: ^0.1.2
  json_annotation: 3.0.1
  dio: 3.0.9
  flutter_custom_dialog: 1.0.4
  sliding_up_panel: 1.0.2
  flutter_spinkit: 4.1.2
  sticky_and_expandable_list: 0.2.3
  oktoast: 2.3.2
  scoped_model: 1.0.1
  provider: 4.0.4
  charts_flutter: 0.9.0
  connectivity: 0.4.4
  localstorage: ^3.0.0
  extended_image: 0.7.2
  extended_image_library: 0.2.1
  sticky_headers:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.2
  json_serializable: ^3.2.5


dependency_overrides:
  analyzer: 0.39.17
  dart_style: 1.3.6

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  module:
    androidX: false
    androidPackage: com.litedu.flutter_module
    iosBundleIdentifier: com.litedu.flutterModule

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true